---

- fail: msg="You must define backup_user, backup_access_key and backup_secret_key"
  when: backup_access_key is not defined or
    backup_secret_key is not defined or
    backup_user is not defined

- include: s3cmd.yml tags=s3cmd
- include: backup.yml tags=backup
