# Installs S3CMD and sets up the config file for the backup user
- name: Backup - S3CMD dependencies
  apt: name="python-pip" state=latest

- name: Backup - S3CMD installation
  pip: name=s3cmd state=present version=1.6.1

- name: Adds S3 credentials
  template: >
    src=../templates/s3cmd.j2
    dest="{{ backup_config_dir }}/s3cfg"
    owner={{ backup_user }}
    mode=600
